title: Han's Blog Site
author:
  name: han shu
  email: hanshu.npu@gmail.com

tagline: Home Page

site_name: blog.hanshu.org
permalink: /:categories/:title/


icon_link: https://cdn.jsdelivr.net/gh/hannshu/imgs/icon/icon-blog.ico
svg_link: https://cdn.jsdelivr.net/gh/hannshu/imgs/icon/icon-blog.svg

show_excerpts: false 

comments:
  gitalk: true
  gitalk_clientID: '67c377de942eeae81e24'
  gitalk_Secret: 'c462cfd4bf5b9adc7f190d866245686d14524104'
  gitalk_repo: 'blogs'
  gitalk_owner: 'hannshu'
  gitalk_admin: 'hannshu'
  distractionFreeMode: true

minima:
  date_format: "%b %-d, %Y"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# markdown: kramdown

# kramdown:
#   math_engine: katex
