title: blog.hanshu.org
author:
  name: han shu
  email: hanshu.npu@gmail.com
  
site_name: blog.hanshu.org
permalink: /:categories/:path/

icon_link: https://cdn.jsdelivr.net/gh/R1szW7xqoVdA/Vu-jewdLEw--f-_-/icon/icon-blog.ico
svg_link: https://cdn.jsdelivr.net/gh/R1szW7xqoVdA/Vu-jewdLEw--f-_-/icon/icon.svg

show_excerpts: false 

minima:
  date_format: "%b %-d, %Y"

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

markdown: kramdown

kramdown:
  math_engine: katex
